# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Witboost Templates Gallery
repo_name: Templates Gallery
repo_url: https://gitlab.com/AgileFactory/Witboost.Mesh/Templates/witboost.mesh.templatesgallery # TODO change when OSS is released

nav:
  - 'index.md'
  - 'guidelines.md'
  - Examples:
      - 'examples/README.md'
      - 'examples/BasicFields/basic_fields.md'
      - 'examples/Layouts/layouts.md'
      - 'examples/ConditionalFields/conditional_fields.md'
      - 'examples/TableSchemaLayout/table_schema_layout.md'
      - 'examples/RetrieveData/retrieve_data.md'
      - 'examples/DynamicSelect/dynamic_select.md'
      - 'examples/TransformingEntities/transforming_entities.md'
      - 'examples/BaseDataProduct/base_data_product.md'
      - Base Components:
        - 'examples/ComponentMetadata/component_metadata.md'
        - 'examples/BaseStorage/base_storage.md'
        - 'examples/BaseWorkload/base_workload.md'
        - Output Port:
            - 'examples/BaseOutputPort/StreamlinedExperience/base_streamlined_experience.md'
            - 'examples/BaseOutputPort/FullExperience/base_full_experience.md'
  - 'templating_solutions.md'

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode
    - media: "(prefers-color-scheme: light)"
      scheme: witboost-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: witboost-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Poppins
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - navigation.footer
    - content.code.copy
  icon:
    repo: fontawesome/brands/gitlab
    edit: material/file-document-edit-outline
  logo: ./img/logo/witboost_logo.svg
  favicon: ./img/logo/witboost_favicon.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2024 Agile Lab.
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/agile-lab
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/agilelab_official/
    - icon: fontawesome/brands/medium
      link: https://medium.com/agile-lab-engineering
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/agile__lab
    - icon: fontawesome/brands/github
      link: https://github.com/agile-lab-dev
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCTWdhr7_4JmZIpZFhMdLzAA

