apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: ${{ values.description | dump }}
spec:
  type: workload
  lifecycle: experimental
  owner: ${{ values.developmentGroup | dump }}
  mesh:
    description: ${{ values.description | dump }}
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    readsFrom: {% if values.readsFrom | length > 0 %}{% for i in values.readsFrom %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    specific:
      driverCores: ${{ values.driverCores }}
      driverMemory: ${{ values.driverMemory }}
      executorCores: ${{ values.executorCores }}
      executorMemory: ${{ values.executorMemory }}
      numExecutors: ${{ values.numExecutors }}
      schedule: {% if values.enableScheduling %}
        cronExpression: ${{ values.cronExpression }}
        startDate: ${{ values.startDate }}
        endDate: ${{ values.endDate }}
      {% else %}null{% endif %}


