# it is important to use this apiVersion
apiVersion: witboost.com/v1
kind: EditTemplate
metadata:
  name: edit-workload-base-full-experience.1
  title: Workload Edit Template
  description: Edit a Workload of a Data Product
  tags:
    - edit
    - workload
spec:
  owner: agilelab
  useCaseTemplateId:
    - urn:dmb:utm:workload-base-full-experience-template:0.0.0
  parameters:
    - title: Update Workload
      description: |
        This wizard will allow you to edit the metadata for a previously created Workload.

        Most metadata is editable but some (like the name, domain, data product etc) are not; their fields will be read-only.

        Some of the files in the component's repository cannot be updated by this wizard, namely:
        - **Documentation**: `README.md`, `docs/index.md`, etc
        - **CI/CD**: `.gitlab-ci-yaml`
        You need to take care of updating these yourself, as given their nature it's hard to do automatically and they are often edited manually after the component's creation.

    - title: Update component metadata
      description: update basic information for this component.
      required:
        - description
      properties:
        name:
          title: Name
          type: string
          description: Not editable. The name of the component.
          ui:disabled: true
        description:
          title: Description
          type: string
          description: Help others understand what this Workload is for
        domain:
          title: Domain
          type: string
          description: Not editable. Domain of the Data Product this component belongs to
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Domain
          ui:disabled: true
        dataproduct:
          title: Data Product
          type: string
          description: Not editable. Data Product this component belongs to
          ui:field: EntityPicker
          ui:filter:
            - fieldName: domain
              entityPath: spec.domain
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - System
          ui:disabled: true
        identifier:
          title: Identifier
          type: string
          description: Autogenerated from the information above. A unique identifier for the component. It will not be editable after creation and is a string composed of [a-zA-Z] separated by any of [-_].
          ui:field: ComponentIdentifierPicker
          ui:options:
            allowArbitraryValues: false
        developmentGroup:
          title: Development Group
          type: string
          description: Automatically selected from the Data Product metadata. Data Product development group.
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.owner
          ui:options:
            allowArbitraryValues: false
        dependsOn:
          title: Dependencies
          type: array
          description: |
            A component could depend on other components in the same Data Product. This information will be used to deploy the components in such an order that their dependencies already exist.

            **Warning**: be careful not to select this component as its own dependency, otherwise it will become undeployable until you edit it again and remove that circular dependency.
          default: []
          items:
            type: string
            ui:field: EntityRelationsPicker
            ui:fieldName: dataproduct
            relation: hasPart
        readsFrom:
          title: Reads from
          type: array
          default: []
          items:
            type: string
            ui:field: ReadsFromPicker
          description: This is filled only for DataPipeline workloads and it represents the list of output ports or external systems that is reading
        tags:
          title: Tags
          type: array
          description: Tags for the component
          default: []
          items:
            type: string

    - title: Update Workload job details
      description: Example of the details a workload may have. Here we assume a job with drivers and executors
      properties:
        driverCores: 
          title: Driver Cores
          type: integer
          description: Number of Driver Cores (If specified must be a positive integer)
        driverMemory:
          title: Driver Memory
          type: string
          description: Driver Memory
          ui:field: RegexPicker
          validation:
            errorMessage: The memory specification should be an integer followed by a size unit suffix ("k", "m", "g" or "t")
            regularExpression: ^\d+[kmgt]$
        executorCores: 
          title: Executor Cores
          type: integer
          description: Number of Executor Cores (If specified must be a positive integer)
        executorMemory:
          title: Executor Memory
          type: string
          description: Executor Memory
          ui:field: RegexPicker
          validation:
            errorMessage: The memory specification should be an integer followed by a size unit suffix ("k", "m", "g" or "t")
            regularExpression: ^\d+[kmgt]$
        numExecutors: 
          title: Number of executors
          type: integer
          description: Number of executors (If specified must be a positive integer)

    - title: Update Workload job scheduling
      description: Example of the details a workload may have. Here we assume a job with scheduling
      properties:
        enableScheduling:
          type: boolean
          title: Enable scheduling
      allOf:
        - if:
            properties:
              enableScheduling:
                const: true
          then:
            properties:
              cronExpression:
                title: Cron expression
                type: string
                description: "Cron expression (format: Min Hour DayOfMonth Month DayOfWeek)"
              startDate:
                title: Start Date
                type: string
                format: date-time
              endDate:
                title: End Date
                type: string
                format: date-time
            required:
              - cronExpression
              - startDate
              - endDate
          else:
            properties:
              {}

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./edit-skeleton
        targetPath: .
        values:
          name: '${{ parameters.name }}'
          description: '${{ parameters.description }}'
          domain: '${{ parameters.domain }}'
          dataproduct: '${{ parameters.dataproduct }}'
          identifier: '${{ parameters.identifier }}'
          developmentGroup: '${{ parameters.developmentGroup }}'
          dependsOn: '${{ parameters.dependsOn }}'
          readsFrom: '${{ parameters.readsFrom }}'
          tags: '${{ parameters.tags }}'
          driverCores: '${{ parameters.driverCores }}'
          driverMemory: '${{ parameters.driverMemory }}'
          executorCores: '${{ parameters.executorCores }}'
          executorMemory: '${{ parameters.executorMemory }}'
          numExecutors: '${{ parameters.numExecutors }}'
          enableScheduling: '${{ parameters.enableScheduling }}'
          cronExpression: '${{ parameters.cronExpression }}'
          startDate: '${{ parameters.startDate | truncate(19, true, "Z") }}'
          endDate: '${{ parameters.endDate | truncate(19, true, "Z") }}'
